global:
  scrape_interval:  5s
  external_labels:
    monitor:  'profile-monitor'

scrape_configs:
  - job_name: 'profile'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.0.6:8189']