server:
  port: 8091
  servlet:
    context-path: /api/public-info
management:
  server:
    port: 8190
  endpoint:
    shutdown:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://test-bank-db:5432/postgres?currentSchema=public_bank_information
    username: postgres
    password: secretpassword
  liquibase:
    default-schema: public_bank_information
    change-log: db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  application:
    name: public-info-app
